### ISSUE TITLE
Option to exit from any story at any time

### ISSUE THREAD

**Issue by alpha-app** [santa112358/story#4] opened 2021-01-16 00:03 UTC
As of now there is no option to close the story view, we have to view all the stories to go back to the intended page.

**Comment by santa112358** [comment] 2021-01-17 07:14
@alpha-app
I think that is the part you can implement in `itemBuilder`. If you are not sure how to do it, let me know and I will show the example. Thank you.

**Comment by santa112358** [comment] 2021-01-26 05:46
Now I close this issue. Please reopen this if you have any questions about this.

**Comment by tatoline** [comment] 2021-02-05 17:30
> @alpha-app
> I think that is the part you can implement in `itemBuilder`. If you are not sure how to do it, let me know and I will show the example. Thank you.

Can you share an example about that? Like a cross icon on top right to call pop()

**Comment by santa112358** [comment] 2021-02-06 04:27
@tatoline @alpha-app 
Updated version to 0.3.0+1 and you can see the way to implement that in example: https://github.com/santa112358/story/blob/main/example/lib/main.dart#L113-L120

**Comment by tatoline** [comment] 2021-02-06 12:08
@santa112358 
Have you tried what you did? I had already tried the following code before writing here to ask you:

> GestureDetector(
                          child: Icon(
                            Icons.cancel_outlined,
                            color: Colors.white,
                            size: 20,
                          ),
                        onTap: () => Navigator.pop(context),
                      ),

But the problem is, next/previous story gesture detection is overlapping on the cross button, so your code too. Instead of closing the story (pop), just go to next story although it's the last element of the Stack. Just try your own code and you will get what I mean. If it was CSS code, I would change the z-index of the cross button.

**Comment by santa112358** [comment] 2021-02-06 12:16
@tatoline 
My apologies. I haven't checked if the onPressed works or not, but now I got the problem. itemBuilder is under the gesture detectors, so gesture actions are disabled in itemBuilder. 

Thank you for telling this. I'll fix this.

**Comment by santa112358** [comment] 2021-02-06 19:05
@tatoline @alpha-app 
Updated to v0.4.0 and added the new builder `gestureItemBuilder` which allows you to use gesture widgets. Please check the example: https://github.com/santa112358/story/blob/main/example/lib/main.dart#L144-L159

Thank you.

**Closed** 2021-02-07 02:14 UTC

**Comment by tatoline** [comment] 2021-02-07 12:14
@santa112358 
Thanks for your quick reply and solution. I will update and try asap. Nice support thank you :)
